export const icons = {
    Arrow_bot_right : require('./Arrow_bot_right.png'),
    Arrow_left : require('./Arrow_left_1.png'),
    Arrow_right : require('./Arrow_right_1.png'),
    Arrow_right_green: require('./Arrow_right_green_1.png'),
    Calender : require('./Calender_1.png'),
    Calender_active : require('./Calender_active_1.png'),
    Caree : require('./Caree_1.png'),
    Caree_active : require('./Caree_active_1.png'),
    Heart : require('./Heart_1.png'),
    Heart_red : require('./Heart_red_12_11.png'),
    Heart_white : require('./Heart_white_12_11.png'),
    Home_active : require('./Home_active_1.png'),
    Home : require('./Home_1.png'),
    Menu : require('./Menu_1.png'),
    Menu_active: require('./Menu_active_1.png'),
    Notification : require('./Notification_14_17.png'),
    Profile : require('./Profile_1.png'),
    Profile_active : require('./Profile_active_1.png'),
    Search : require('./Search_1.png'),
    Search_active : require('./Search_active_1.png'),
    Setting : require('./Settings_1.png'),
    Desktop: require('./Desktop_1.png'),
    
}